server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: mbp
    password: 890
    url: jdbc:mysql://localhost:3306/baubiblio
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
